const COURSE_DATA=window.COURSE_DATA||[];
const META=Object.assign({
  id:'lecture-html-engine',
  title:'Lecture HTML Engine',
  homeKicker:'LECTURE HTML ENGINE',
  homeTitleHtml:'Lecture HTML <em>Engine</em>',
  description:'一个支持全屏、逐条显示、讲稿、搜索和数位板批注的离线课程系统。',
  courseCount:COURSE_DATA.length,
  totalSlides:COURSE_DATA.reduce((n,c)=>n+c.slides.length,0)
},window.LECTURE_META||{});
const STORE_PREFIX=(META.id||'lecture-html-engine')+':v1';
document.title=META.title;
const flatSlides=COURSE_DATA.flatMap(c=>c.slides.map(s=>({...s,courseTitle:c.title,courseHook:c.hook,minutes:c.minutes})));
const state={view:'home',globalIndex:0,reveal:0,notesOpen:false,drawMode:false,tool:'pen',color:'#FF5A1F',width:5,activePointer:null,stroke:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function safeGet(k,fallback){try{const v=localStorage.getItem(k);return v===null?fallback:JSON.parse(v)}catch(_){return fallback}}
function safeSet(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_){showToast('浏览器阻止了本地保存，本次仍可继续使用');return false}}
const AnnotationStore={ink:safeGet(STORE_PREFIX+':ink',{}),redo:{},save(){safeSet(STORE_PREFIX+':ink',this.ink)},key(){return flatSlides[state.globalIndex]?.id},list(){return this.ink[this.key()]||[]}};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.add('hidden'),1800)}
function renderHome(){state.view='home';$('#homeView').classList.remove('hidden');$('#lectureView').classList.add('hidden');closeModal();$('#homeView').innerHTML=`<header class="home-head"><div><div class="eyebrow home-kicker">${esc(META.homeKicker)}</div><h1 class="home-title">${META.homeTitleHtml||esc(META.title)}</h1><div class="home-actions"><button class="primary" data-home-action="resume">${safeGet(STORE_PREFIX+':progress',null)?'继续上次阅读':'从第一课开始'}</button><button class="chrome-btn" data-home-action="map">打开知识地图</button><button class="chrome-btn" data-home-action="search">搜索 ${META.totalSlides} 页</button></div></div><div class="home-meta"><strong>${META.courseCount} COURSES / ${META.totalSlides} PAGES</strong><p>${esc(META.description)}</p><span class="tag orange">OFFLINE · LOCAL FIRST</span></div></header><section class="course-grid">${COURSE_DATA.map(c=>`<button class="course-card" data-course="${c.id}" data-id="${c.id}"><span class="tag ${+c.id%3===0?'purple':'orange'}">COURSE ${c.id} · ${c.minutes} MIN</span><h2>${esc(c.title)}</h2><p class="card-hook">${esc(c.hook)}</p><div class="card-foot"><span>${c.slides.length} PAGES</span><span>${esc(c.terms.slice(0,2).join(' / '))}</span></div></button>`).join('')}</section>`}
function openCourse(id){const i=flatSlides.findIndex(s=>s.courseId===String(id).padStart(2,'0'));goToSlide(i<0?0:i)}
function goToSlide(index,reveal=0){state.view='lecture';state.globalIndex=Math.max(0,Math.min(flatSlides.length-1,index));state.reveal=reveal;$('#homeView').classList.add('hidden');$('#lectureView').classList.remove('hidden');renderSlide();safeSet(STORE_PREFIX+':progress',{index:state.globalIndex,reveal:state.reveal});}
function themeFor(s){if(['chapter','next'].includes(s.layout))return 'dark';if(['hook','signal'].includes(s.layout)&&s.globalIndex%2===0)return 'orange';return 'light'}
function renderSlide(){const s=flatSlides[state.globalIndex],theme=themeFor(s);const formula=s.formula?`<div class="formula" data-step="1">${esc(s.formula)}</div>`:'';const offset=formula?1:0;$('#stage').innerHTML=`<article class="slide-shell ${theme} layout-${esc(s.layout)}"><header class="slide-header"><div class="slide-course">COURSE ${s.courseId} / ${esc(s.courseTitle)}</div><div class="slide-type">${esc(s.label)} · ${esc(s.authority)}</div></header><div class="slide-body"><h1 class="slide-title">${esc(s.title)}</h1><p class="slide-deck">${esc(s.goal)}</p>${formula}<ol class="point-list">${s.points.map((p,i)=>`<li class="point" data-step="${i+1+offset}" data-n="0${i+1}">${esc(p)}</li>`).join('')}</ol><div class="terms">${s.terms.slice(0,5).map(t=>`<span class="term">${esc(t)}</span>`).join('')}</div><div class="ornament" aria-hidden="true"><i class="o-ring"></i><i class="o-line"></i></div></div><footer class="slide-footer"><div class="source">SOURCE · ${esc(s.source)}<br>${esc(s.authority)} · ${esc(s.label)}</div><div class="page-code">${String(s.globalIndex).padStart(3,'0')} / ${META.totalSlides}</div></footer></article>`;applyReveal();renderNotes();updateHud();resizeStage();redrawInk()}
function applyReveal(){const items=$$('#stage [data-step]');items.forEach(el=>el.classList.toggle('unrevealed',+el.dataset.step>state.reveal))}
function nextRevealOrSlide(){const count=$$('#stage [data-step]').length;if(state.reveal<count){state.reveal++;applyReveal();safeSet(STORE_PREFIX+':progress',{index:state.globalIndex,reveal:state.reveal})}else goToSlide(state.globalIndex+1)}
function prevSlide(){goToSlide(state.globalIndex-1,99)}
function nextCourse(){const id=flatSlides[state.globalIndex].courseId;const next=COURSE_DATA.find(c=>+c.id>+id);if(next)openCourse(next.id);else showToast('已经是最后一课')}
function prevCourse(){const id=flatSlides[state.globalIndex].courseId;const prev=[...COURSE_DATA].reverse().find(c=>+c.id<+id);if(prev)openCourse(prev.id);else showToast('已经是第一课')}
function updateHud(){const s=flatSlides[state.globalIndex];$('#hudCourse').innerHTML=`COURSE <strong>${s.courseId}</strong> · ${s.localIndex}/${s.localTotal}`;$('#hudPage').textContent=`${s.globalIndex}/${META.totalSlides}`;$('#progressFill').style.width=`${s.globalIndex/META.totalSlides*100}%`}
function renderNotes(){const s=flatSlides[state.globalIndex];$('#notesDrawer').innerHTML=`<h2>讲者备注</h2><span class="tag orange">${s.id}</span><p>${esc(s.speakerNotes)}</p><p class="cue"><strong>转场句</strong><br>${esc(s.bridge)}</p><p><strong>易错点：</strong>${esc(s.pitfall)}</p>`}
function toggleNotes(force){state.notesOpen=typeof force==='boolean'?force:!state.notesOpen;$('#notesDrawer').classList.toggle('hidden',!state.notesOpen)}
function toggleFullscreen(){const target=$('#lectureView')||document.documentElement;if(!document.fullscreenElement){target.requestFullscreen?.().catch(()=>showToast('当前浏览器不允许进入演示全屏；也可按浏览器 F11'))}else document.exitFullscreen?.()}
function resizeStage(){const wrap=$('.stage-wrap');if(!wrap||state.view!=='lecture')return;const scale=Math.min((wrap.clientWidth-8)/1600,(wrap.clientHeight-8)/900);$('#stage').style.transform=`scale(${scale})`;const c=$('#annotationCanvas');const r=$('#stage').getBoundingClientRect();Object.assign(c.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'})}
function closeModal(){$('#modalRoot').innerHTML=''}
function modal(title,body){$('#modalRoot').innerHTML=`<div class="modal-backdrop" role="dialog" aria-modal="true"><section class="panel"><header class="panel-head"><h2>${esc(title)}</h2><button class="chrome-btn" data-modal-close>ESC / 关闭</button></header>${body}</section></div>`}
function openCourseMenu(){modal('课程目录',`<div class="modal-grid">${COURSE_DATA.map(c=>`<button class="modal-item" data-course-jump="${c.id}"><small>COURSE ${c.id} · ${c.slides.length} PAGES</small><h3>${esc(c.title)}</h3><p>${esc(c.hook)}</p></button>`).join('')}</div>`)}
function openOverview(){modal(`全书 ${META.totalSlides} 页总览`,`<div class="modal-grid">${flatSlides.map((s,i)=>`<button class="modal-item" data-slide-jump="${i}"><small>${String(s.globalIndex).padStart(3,'0')} · C${s.courseId}</small><div>${esc(s.title)}</div></button>`).join('')}</div>`)}
function openKnowledgeMap(){modal('知识地图',`<p>橙色节点标识主线课程；紫色与绿色边框提示结构转折。点击任意节点进入。</p><div class="map-grid">${COURSE_DATA.map(c=>`<button class="map-node" data-course-jump="${c.id}"><strong>${c.id}</strong>${esc(c.title)}<small>${esc(c.terms.slice(0,3).join(' · '))}</small></button>`).join('')}</div>`)}
function openSearch(){modal('全文搜索',`<input id="searchInput" class="search-input" autocomplete="off" placeholder="输入概念、电影、人物、来源或页码…"><div id="searchResults" class="search-results"></div>`);setTimeout(()=>{$('#searchInput')?.focus();runSearch('')},0)}
function runSearch(q){const box=$('#searchResults');if(!box)return;const needle=q.trim().toLowerCase();const hits=(needle?flatSlides.filter(s=>[s.title,s.goal,s.authority,s.source,...s.points,...s.terms].join(' ').toLowerCase().includes(needle)):flatSlides.slice(0,18)).slice(0,80);box.innerHTML=hits.map(s=>`<button class="search-hit" data-slide-jump="${s.globalIndex-1}"><strong>${String(s.globalIndex).padStart(3,'0')} / C${s.courseId}</strong><span>${esc(s.title)}<br><small>${esc(s.points[0])}</small></span></button>`).join('')||'<p>没有匹配结果。试试“抽灵机”“焦虑”或“银翼杀手”。</p>'}

function renderInkToolbar(){const colors=['#FF5A1F','#6E4AFF','#B9FF4A','#000000','#FFFFFF'];$('#inkToolbar').innerHTML=`<button class="chrome-btn" data-tool="pen">笔</button><button class="chrome-btn" data-tool="highlighter">荧光</button><button class="chrome-btn" data-tool="eraser">橡皮</button>${colors.map(c=>`<button class="tool-swatch ${state.color===c?'active':''}" data-color="${c}" style="background:${c}" aria-label="颜色 ${c}"></button>`).join('')}<input data-width type="range" min="2" max="36" value="${state.width}" aria-label="笔宽"><button class="chrome-btn" data-ink="undo">↶</button><button class="chrome-btn" data-ink="redo">↷</button><button class="chrome-btn" data-ink="clear">清页</button>`}
function toggleDraw(force){state.drawMode=typeof force==='boolean'?force:!state.drawMode;$('#lectureView').classList.toggle('draw-on',state.drawMode);$('#inkToolbar').classList.toggle('hidden',!state.drawMode);if(state.drawMode)renderInkToolbar()}
function canvasPoint(e){const r=$('#annotationCanvas').getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,p:e.pressure||.5}}
function beginStroke(e){if(!state.drawMode||state.activePointer!==null)return;e.preventDefault();state.activePointer=e.pointerId;$('#annotationCanvas').setPointerCapture?.(e.pointerId);state.stroke={tool:state.tool,color:state.color,width:state.width,points:[canvasPoint(e)]};AnnotationStore.redo[AnnotationStore.key()]=[]}
function extendStroke(e){if(e.pointerId!==state.activePointer||!state.stroke)return;e.preventDefault();state.stroke.points.push(canvasPoint(e));redrawInk(state.stroke)}
function endStroke(e){if(e.pointerId!==state.activePointer||!state.stroke)return;state.stroke.points.push(canvasPoint(e));const key=AnnotationStore.key();AnnotationStore.ink[key]=[...(AnnotationStore.ink[key]||[]),state.stroke];state.stroke=null;state.activePointer=null;AnnotationStore.save();redrawInk()}
function undoStroke(){const key=AnnotationStore.key(),list=AnnotationStore.ink[key]||[];if(!list.length)return;(AnnotationStore.redo[key]??=[]).push(list.pop());AnnotationStore.save();redrawInk()}
function redoStroke(){const key=AnnotationStore.key(),redo=AnnotationStore.redo[key]||[];if(!redo.length)return;(AnnotationStore.ink[key]??=[]).push(redo.pop());AnnotationStore.save();redrawInk()}
function clearPageInk(){const key=AnnotationStore.key();if(!(AnnotationStore.ink[key]||[]).length)return;AnnotationStore.redo[key]=AnnotationStore.ink[key];AnnotationStore.ink[key]=[];AnnotationStore.save();redrawInk();showToast('本页批注已清除，可用撤销恢复')}
function redrawInk(extra){const c=$('#annotationCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);[...AnnotationStore.list(),...(extra?[extra]:[])].forEach(st=>drawStroke(ctx,st))}
function drawStroke(ctx,st){if(!st.points?.length)return;ctx.save();ctx.globalCompositeOperation=st.tool==='eraser'?'destination-out':'source-over';ctx.globalAlpha=st.tool==='highlighter'?.25:1;ctx.strokeStyle=st.color;ctx.lineCap='round';ctx.lineJoin='round';for(let i=1;i<st.points.length;i++){const a=st.points[i-1],b=st.points[i];ctx.beginPath();ctx.lineWidth=st.width*(st.tool==='highlighter'?4:1)*(.65+.7*(b.p||.5));ctx.moveTo(a.x*1600,a.y*900);ctx.lineTo(b.x*1600,b.y*900);ctx.stroke()}ctx.restore()}

function handleAction(a){({prev:prevSlide,next:nextRevealOrSlide,prevCourse,nextCourse,search:openSearch,menu:openCourseMenu,map:openKnowledgeMap,notes:toggleNotes,draw:toggleDraw,home:renderHome,fullscreen:toggleFullscreen,overview:openOverview}[a]||(()=>{}))()}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a)handleAction(a);const c=e.target.closest('[data-course]')?.dataset.course;if(c)openCourse(c);const cj=e.target.closest('[data-course-jump]')?.dataset.courseJump;if(cj){closeModal();openCourse(cj)}const sj=e.target.closest('[data-slide-jump]')?.dataset.slideJump;if(sj!==undefined){closeModal();goToSlide(+sj)}if(e.target.closest('[data-modal-close]'))closeModal();const ha=e.target.closest('[data-home-action]')?.dataset.homeAction;if(ha==='resume'){const p=safeGet(STORE_PREFIX+':progress',{index:0,reveal:0});goToSlide(p.index,p.reveal)}if(ha==='map')openKnowledgeMap();if(ha==='search')openSearch();const tool=e.target.closest('[data-tool]')?.dataset.tool;if(tool){state.tool=tool;showToast(`批注工具：${tool}`)}const color=e.target.closest('[data-color]')?.dataset.color;if(color){state.color=color;renderInkToolbar()}const ink=e.target.closest('[data-ink]')?.dataset.ink;if(ink==='undo')undoStroke();if(ink==='redo')redoStroke();if(ink==='clear')clearPageInk()});
document.addEventListener('input',e=>{if(e.target.id==='searchInput')runSearch(e.target.value);if(e.target.matches('[data-width]'))state.width=+e.target.value});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea')){if(e.key==='Escape')closeModal();return}if(e.key==='Escape'){closeModal();toggleDraw(false);return}const key=e.code==='Space'?'Space':e.key;if(['Space','ArrowLeft','ArrowRight','Home','End'].includes(key))e.preventDefault();if(key==='Space')nextRevealOrSlide();else if(key==='ArrowRight')goToSlide(state.globalIndex+1);else if(key==='ArrowLeft')prevSlide();else if(key==='Home')goToSlide(0);else if(key==='End')goToSlide(flatSlides.length-1);else if(key==='n'||key==='N')nextCourse();else if(key==='p'||key==='P')prevCourse();else if(key==='d'||key==='D')toggleNotes();else if(key==='h'||key==='H')renderHome();else if(key==='e'||key==='E')toggleDraw();else if(key==='c'||key==='C')openCourseMenu();else if(key==='m'||key==='M')openKnowledgeMap();else if(key==='f'||key==='F')toggleFullscreen();else if(key==='o'||key==='O')openOverview();else if(key==='/')openSearch();else if((e.ctrlKey||e.metaKey)&&key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redoStroke():undoStroke()}});
const canvas=$('#annotationCanvas');['pointerup','pointercancel'].forEach(n=>canvas.addEventListener(n,endStroke));canvas.addEventListener('pointerdown',beginStroke);canvas.addEventListener('pointermove',extendStroke);window.addEventListener('resize',resizeStage);document.addEventListener('fullscreenchange',resizeStage);
renderHome();
